package nave:db

interface driver {
    resource connection {
        constructor(url: string, db_type: string);
        execute: func(query: string) -> result<u64, string>;
        query: func(query: string) -> result<list<list<string>>, string>;
    }
}
